#!/bin/bash
i=0
ls -t content  | cut -d . -f1 > worklist
perl  -0777 -i -pe 's/_/ /igs' worklist
perl  -0777 -i -pe 's/-/ /igs' worklist
while [ $i -lt 80 ]
do
echo -ne "$(tput setaf 2)="
i=$[$i+1]
done
echo "$(tput sgr 0)"
git add .
if [[ $1 ]] 
then
git commit -m "$1"
else
git commit -m "updates"
fi
git push

DATE=$(date +"%D %T")
echo "$(tput setaf 2)
Committed to tv on $DATE $(tput sgr 0)"
while [ $i -gt 0 ]
do
sleep 0.1
echo -ne "="
i=$[$i-1]
done
open http://fdch.github.io/tv
exit
